apiVersion: v1
kind: Pod
metadata:
 name: my-pod
 labels: 
   environment: staging
   team: kube-team
spec:
 containers:
   - name: my-container
     image: ubuntu
     command: ["/bin/bash", "-ec", "sleep infinity"] 
     resources:
       limits:
        cpu: 1
---        
apiVersion: v1
kind: Pod
metadata:
 name: my-pod2
 labels: 
   environment: staging
   team: kube-team
spec:
 containers:
   - name: my-container
     image: ubuntu
     command: ["/bin/bash", "-ec", "sleep infinity"] 
     resources:
       limits:
        cpu: 1
---        
apiVersion: v1
kind: Pod
metadata:
 name: my-pod2
 labels: 
   environment: staging
   team: kube-team
spec:
 containers:
   - name: my-container
     image: ubuntu
     command: ["/bin/bash", "-ec", "sleep infinity"] 
     resources:
       limits:
        cpu: 1
---        
apiVersion: v1
kind: Pod
metadata:
 name: my-pod2
 labels: 
   environment: staging
   team: kube-team
spec:
 containers:
   - name: my-container
     image: ubuntu
     command: ["/bin/bash", "-ec", "sleep infinity"] 
     resources:
       limits:
        cpu: 1
---        
apiVersion: v1
kind: Pod
metadata:
 name: my-pod2
 labels: 
   environment: staging
   team: kube-team
spec:
 containers:
   - name: my-container
     image: ubuntu
     command: ["/bin/bash", "-ec", "sleep infinity"] 
     resources:
       limits:
        cpu: 1
---        
apiVersion: v1
kind: Pod
metadata:
 name: my-pod2
 labels: 
   environment: staging
   team: kube-team
spec:
 containers:
   - name: my-container
     image: ubuntu
     command: ["/bin/bash", "-ec", "sleep infinity"] 
     resources:
       limits:
        cpu: 1
---        
apiVersion: v1
kind: Pod
metadata:
 name: my-pod2
 labels: 
   environment: staging
   team: kube-team
spec:
 containers:
   - name: my-container
     image: ubuntu
     command: ["/bin/bash", "-ec", "sleep infinity"] 
     resources:
       limits:
        cpu: 1
---        
apiVersion: v1
kind: Pod
metadata:
 name: my-pod2
 labels: 
   environment: staging
   team: kube-team
spec:
 containers:
   - name: my-container
     image: ubuntu
     command: ["/bin/bash", "-ec", "sleep infinity"] 
     resources:
       limits:
        cpu: 1
        