---
# - hosts: 127.0.0.1
#   tasks:
#     - name: local test
#       local_action: copy content="here" dest=/root/setup.txt
- hosts: webservers
  remote_user: root
  pre_tasks:
    - name: report back
      local_action: copy content="Apache installing on three hosts" dest=/root/status.txt

  post_tasks:
    - name: report back
      local_action: copy content="Apache installed on {{ansible_hostname}}" dest=/root/status.txt
  roles: 
    - geerlingguy.apache
    
- hosts: webservers
  remote_user: root
  pre_tasks:
    - name: report back
      local_action: copy content="PHP installing on three hosts" dest=/root/status.txt

  post_tasks:
    - name: report back
      local_action: copy content="PHP installed on {{ansible_hostname}}" dest=/root/status.txt
  roles: 
    - geerlingguy.php
    
- hosts: webservers
  remote_user: root
  pre_tasks:
    - name: report back
      local_action: copy content="Apache PHP FPM installing on three hosts" dest=/root/status.txt

  post_tasks:
    - name: report back
      local_action: copy content="Apache PHP FPM installed on {{ansible_hostname}}" dest=/root/status.txt
  roles: 
    - geerlingguy.apache-php-fpm
    
- hosts: webservers
  roles:
    - { role: Datadog.datadog, become: yes }
  vars:
    datadog_api_key: "{{ lookup('env', 'DD_API_KEY')}}"
  tasks:
    - name: report back
      local_action: copy content="Datadog Agent installed on {{ansible_hostname}}" dest=/root/status.txt
  pre_tasks:
    - name: report back
      local_action: copy content="Datadog Agent installing on all hosts" dest=/root/status.txt
     
