---
# - hosts: 127.0.0.1
#   tasks:
#     - name: local test
#       local_action: copy content="here" dest=/root/setup.txt
- hosts: webservers
  remote_user: root
  pre_tasks:
    - name: report back
      local_action: copy content="Apache installing on three hosts" dest=/root/status.txt
  tasks:
    - name: Update Apt Cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Install Apache
      apt: 
        name: apache2
        state: present
    - name: Enable Mod Status
      blockinfile:
        block: |
          ExtendedStatus ON
          <Location /server-status>
            SetHandler server-status
            Require all granted
          </Location>
          ServerName {{ansible_hostname}}
        dest: /etc/apache2/apache2.conf
    - name: restart apache
      shell: apachectl restart
      
  post_tasks:
    - name: report back
      local_action: copy content="Apache installed on {{ansible_hostname}}" dest=/root/status.txt
  
- hosts: webservers
  roles:
    - { role: Datadog.datadog, become: yes }
  vars:
    datadog_api_key: "{{ lookup('env', 'DD_API_KEY')}}"
    datadog_checks:
      apache:
        init_config:
        instances:
          - apache_status_url: http://localhost/server-status?auto 
  tasks:
    - name: report back
      local_action: copy content="Datadog Agent installed on {{ansible_hostname}}" dest=/root/status.txt
  pre_tasks:
    - name: report back
      local_action: copy content="Datadog Agent installing on all hosts" dest=/root/status.txt
     
