---
- hosts: all
  vars:
    DD_API_KEY: "{{ lookup('env', 'DD_API_KEY')}}"
  roles:
    - { role: Datadog.datadog, become: yes, datadog_api_key: '{{ DD_API_KEY }}' }
- hosts: webservers
  remote_user: root
  tasks:
    - name: install apache
      apt:
        name: apache2
    - name: setup datadog integration
      datadog_checks:
        apache:
          init_config:
          instances:
            - apache_status_url: http://localhost/server-status?auto
            
