---
- hosts: webservers
  retries: 10
  roles:
    - { role: Datadog.datadog, become: yes }
  vars:
    datadog_api_key: "{{ lookup('env', 'DD_API_KEY')}}"
     

- hosts: webservers
  remote_user: root
  tasks:
    - name: install apache
      apt:
        name: apache2
    