---
- hosts: all
  tasks: 
    - name: stop auto updates
      shell: systemctl disable --now apt-daily{,-upgrade}.{timer,service}
    - name: kill apt
      shell: pkill apt
    - name: Wait for automatic system updates
      shell: while pgrep unattended; do sleep 2; done;

- hosts: webservers
  roles:
    - { role: Datadog.datadog, become: yes }
  vars:
    datadog_api_key: "{{ lookup('env', 'DD_API_KEY')}}"
     

- hosts: webservers
  remote_user: root
  tasks:
    - name: install apache
      apt:
        name: apache2
    