version: '3'
services:
  redis:
    image: redis
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 8000:8000
  datadog:
    links:
    - redis
    - nginx
    image: datadog/agent:latest
    environment:
    - DD_API_KEY
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /proc/mounts:/host/proc/mounts:ro
    - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  
